#! /usr/bin/env bash
if ! [[ "$MOD_VERSION" =~ ^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(-((0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(\.(0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(\+([0-9a-zA-Z-]+(\.[0-9a-zA-Z-]+)*))?$ ]]; then
  echo "ERR: $MOD_VERSION_PROPERTY in $GRADLE_PROPERTIES_PATH is not a valid semantic version"
  exit 1
fi

if ! [[ "$CI_COMMIT_TAG" =~ ^v?$MOD_VERSION$ ]]; then
  echo "ERR: CI_COMMIT_TAG \"${CI_COMMIT_TAG}\" does not match $MOD_VERSION_PROPERTY \"${MOD_VERSION}\""
  exit 2
fi

exit 0