#! /usr/bin/env bash

if [ -z "$MODRINTH_VERSIONS_TOKEN" ]; then
  echo "ERR: Modrinth Personal Access Token not set"
  exit 1
fi

if [ -z "$MOD_VERSION" ]; then
  echo "ERR: Mod version not set"
  exit 2
fi

VERSION_TYPE=release

POST_BODY_JSON=$(jq -n \
  --arg name              "Version: ${MOD_VERSION}" \
  --arg version_number    "${MOD_VERSION}" \
  --arg changelog         "${CI_COMMIT_TAG_MESSAGE}" \
  --arg dependencies      [] \
  --arg game_versions     ["${MINECRAFT_VERSION}"] \
  --arg version_type      "${VERSION_TYPE}" \
  --arg loaders           ["fabric"] \
  --arg featured          true \
  --arg status            "listed" \
  --arg project_id        "3Yfib80e" \
  --arg file_parts        ["copying-table-${MOD_VERSION}.jar"] \
  '$ARGS.named'
)

echo "$POST_BODY_JSON"

curl -v -X POST -H "Authorization: ${MODRINTH_VERSIONS_TOKEN}" "https://api.modrinth.com/v2/version" \
	-F data="${POST_BODY_JSON}" \
	-F file="@build/libs/copying-table-${MOD_VERSION}.jar"
