#! /usr/bin/env bash

if [ -z "$MODRINTH_VERSIONS_TOKEN" ]; then
  echo "ERR: Modrinth Personal Access Token not set"
  exit 1
fi

if [ -z "$MOD_VERSION" ]; then
  echo "ERR: Mod version not set"
  exit 2
fi

VERSION_TYPE=release

POST_BODY_JSON=$(jq -n \
  --argjson name              "Version: ${MOD_VERSION}" \
  --argjson version_number    "${MOD_VERSION}" \
  --argjson changelog         "${CI_COMMIT_TAG_MESSAGE}" \
  --argjson dependencies      [] \
  --argjson game_versions     ["${MINECRAFT_VERSION}"] \
  --argjson version_type      "${VERSION_TYPE}" \
  --argjson loaders           ["fabric"] \
  --argjson featured          true \
  --argjson status            "listed" \
  --argjson project_id        "3Yfib80e" \
  --argjson file_parts        ["copying-table-${MOD_VERSION}.jar"] \
  '$ARGS.named'
)

echo "$POST_BODY_JSON"

curl -v -X POST -H "Authorization: ${MODRINTH_VERSIONS_TOKEN}" "https://api.modrinth.com/v2/version" \
	-F data="${POST_BODY_JSON}" \
	-F file="@build/libs/copying-table-${MOD_VERSION}.jar"
